### ISSUE TITLE
Anything chef-brigade can do to help?

### ISSUE THREAD

**Issue by josephholsten** [librato/papertrail-cookbook#20]
Is there anything @chef-brigade can do to help out? We're probably going to start using this in our infra, so we want to keep it awesome.

If you need any administrative help, want a slack channel, website, testing infra &c, just let us know. It doesn't need to have the brigade name anywhere on it.

**Comment by mheffner** [comment]
@josephholsten Thanks, at the moment we do not have any issues open: https://github.com/librato/papertrail-cookbook/issues. Happy to accept PRs if you experience problems running this in production.
