### ISSUE TITLE
Not in Supermarket?

### ISSUE THREAD

**Issue by agius** [librato/papertrail-cookbook#24]
At [Hired](https://github.com/hired) we're setting up cookbooks following "the Berkshelf Way™," and have so far been able to specify dependencies in `metadata.rb` to be read by Berkshelf. However, this cookbook isn't on [the Chef Supermarket](https://supermarket.chef.io/cookbooks?utf8=%E2%9C%93&q=papertrail-cookbook), so we have to work around that. We haven't used `knife-github-cookbooks` and I always hesitate to introduce a new dependency, especially one that goes outside our normal workflow.

Any chance y'all could publish this? Thanks!

**Comment by mheffner** [comment]
@troy @eric Any thoughts on this? We're not actively using chef anymore so I fear this repo may fall out of regular maintenance. Should we see if someone in the community wants to take over maintenance?

**Comment by eric** [comment]
Yeah, giving this to the community sounds great.

**Comment by luckymike** [comment]
@mheffner @eric Chef has a [Partner Cookbook Program](https://blog.chef.io/2016/02/23/chef-launches-partner-cookbook-program-to-expand-devops-ready-technology-ecosystem/) that promotes vendor maintained cookbooks. It's a great way to support your customers and it demonstrates to the Chef Community that you encourage strong DevOps and Infrastructure as Code practices.

Any chance you could be convinced to continue maintaining this cookbook and participating? If so, you should contact @jjasghar :)

**Comment by jjasghar** [comment]
Hi! I'm here to help.

Check out https://www.chef.io/partners/cookbooks/ if you are interested :)

Don't hesitate to reach out via jj@chef.io either :)

**Comment by mheffner** [comment]
@luckymike @jjasghar Thanks for the links, we'll take a look and see what needs to be done.

**Comment by troy** [comment]
All, just a small note that we're in the process of arranging some TLC and improvements to this cookbook (as paid consulting work, probably in September). If that falls through, @agius and @jjasghar, I'll contact each of you about ongoing maintenance options. One way or the other, this cookbook will become more actively maintained than it has been as a solely user-maintained one.

**Comment by jjasghar** [comment]
I need to apologize; unfortunately this cookbook doesn't fall in the requirements for the [Chef Partner Cookbook Program](https://www.chef.io/partners/cookbooks/). It looks like that Papertail is owned by Solarwinds not Librato, which is one of the stipulations for the Badge.

On the other hand, there is nothing stopping yall from uploading this cookbook to the Chef [Supermarket](https://supermarket.chef.io) as a community cookbook. :metal:

**Comment by jjasghar** [comment]
I should mention though [collectd-librato-cookbook](https://github.com/librato/collectd-librato-cookbook) looks in line with the CPCP.

**Comment by troy** [comment]
@jjasghar as part of taking over maintenance, we (Papertrail) would move the cookbook repo to `papertrail`'s org. That said, Papertrail and Librato are both owned by SolarWinds. Wouldn't be a big deal if something prevents participating, though - our interest and work is to better support users and improve the end-to-end UX, not marketing.

**Comment by jjasghar** [comment]
@troy makes perfect sense. I'm here to help and I didn't realize yall are both subsiteraries of SolarWinds.

I would like to say that this isn't a marketing push, one of our known problems with the Chef Supermarket is that anyone can push a cookbook up to do _something_. Vendors have asked for a way to show their "offical" ie [cookbooks](https://supermarket.chef.io/cookbooks?utf8=✓&q=&badges%5B%5D=partner&platforms%5B%5D=). 

The CPCP badge is how we've come to that agreement. We also have a [cookbook-guide](https://github.com/chef-partners/cookbook-guide) to vet the Vendors cookbooks and have continued certification via a [Jenkins pipeline](https://github.com/chef-partners/chef-partner-cookbook-program-jjb).

I'm here to help in anyway, don't hesitate to reach out if this might be something you want to look towards in the future.

**Comment by gmccue** [comment]
Just a ping. Any movement on this?

**Comment by troy** [comment]
@gmccue no, no plans to do this in the foreseeable future. Nothing against it, there's just much higher-impact ways to invest time.
